### ISSUE TITLE
Test builds consuming large amount of github action minutes

### ISSUE THREAD

**Issue by ichrisanderson** [android/android-dev-challenge-compose#7]
The test build is setup to use macOS. 1 macOS minute counts as 10 regular minutes on Github actions. 

<img width="527" alt="Screenshot 2021-03-08 at 21 18 08" src="https://user-images.githubusercontent.com/272168/110384079-13eff300-8055-11eb-8385-9cec1fa0dda1.png">

After starting the week1 and week2 challenges my github action minutes have now been spent,  most users will be on a free plan which is capped at 2000 minutes.

Can the tests be disabled?

**Comment by matale** [comment]
Interesting I have done both weeks but it hasn't cost me any minutes it seems I can only see 4 used with multiple build/tests over 10 min, how are you getting the repo, are you also using the "**Use this template**" button? It might be a good idea not to push every commit to save on minutes.

**Comment by ichrisanderson** [comment]
Setup via the "Use this template". Have pushed 7 times on 2 projects looking at the actions log, I don't think that's excessive. I would have pushed  less if it was apparent this workflow is so expensive.

I'm seeing the following, this build cost me over 380 build minutes, 1 macOS minute is 10x the cost.

![Screenshot 2021-03-12 at 09 01 44](https://user-images.githubusercontent.com/272168/110917595-fa2f0400-8311-11eb-8b34-34518da3d74d.png)

Given there aren't any UI tests setup in the template, and the majority of people won't be writing espresso tests can't the connected tests be removed?

**Comment by necatisozer** [comment]
Actions on public repositories are free.

**Comment by ichrisanderson** [comment]
> Actions on public repositories are free.

2000 minutes per month are free. This template used 2040 minutes for me with the first 2 challenges.

**Comment by necatisozer** [comment]
> > Actions on public repositories are free.
> 
> 2000 minutes per month are free. This template used 2040 minutes for me with the first 2 challenges.

No, they are totally free **IF** your repository is public. Your repositories are probably private.
